config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :pray_petitions do
    post '/finished', to: "pray_petitions#finished"
  end

  namespace :admin do
  end

  root 'pray_petitions#new'

  get '/gracias-por-tu-peticion', to: 'pray_petitions#thank_you'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pray_petition.rb
# frozen_string_literal: true

class PrayPetition < ApplicationRecord
  validates :name, presence: true
  validates :pray_for, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

module Admin
  class DashboardController < ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def after_sign_in_path(resource)
    pray_petitions_path
  end
end

app/controllers/pray_petitions_controller.rb
# frozen_string_literal: true

class PrayPetitionsController < ApplicationController
  before_action :authenticate_user!, only: %i[index show edit update destroy]
  before_action :set_pray_petition, only: %i[show edit update destroy finished]

  # GET /pray_petitions or /pray_petitions.json
  def index
    @pray_petitions = PrayPetition.where(read: nil)
  end

  # GET /pray_petitions/1 or /pray_petitions/1.json
  def show; end

  # GET /pray_petitions/new
  def new
    @pray_petition = PrayPetition.new
  end

  # GET /pray_petitions/1/edit
  def edit; end

  # POST /pray_petitions or /pray_petitions.json
  def create
    @pray_petition = PrayPetition.new(pray_petition_params)

    respond_to do |format|
      if @pray_petition.save
        format.html { redirect_to :gracias_por_tu_peticion }
        format.json { render :show, status: :created, location: @pray_petition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pray_petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pray_petitions/1 or /pray_petitions/1.json
  def update
    respond_to do |format|
      if @pray_petition.update(pray_petition_params)
        format.html { redirect_to :gracias_por_tu_peticion }
        format.json { render :show, status: :ok, location: @pray_petition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pray_petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pray_petitions/1 or /pray_petitions/1.json
  def destroy
    @pray_petition.destroy

    respond_to do |format|
      format.html { redirect_to pray_petitions_url, notice: 'Pray petition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def thank_you
    if current_user.present?
      redirect_to pray_petitions_url, notice: 'Peticion agregada.'
    else
      render 'thank_you'
    end
  end

  def finished
    respond_to do |format|
      if @pray_petition.update({ read: 1 })
        format.html { redirect_to pray_petitions_url, notice: 'Peticion Leida.' }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pray_petition
    params[:id] ||= params[:pray_petition_id]
    @pray_petition = PrayPetition.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pray_petition_params
    params.require(:pray_petition).permit(:name, :phone_number, :email, :pray_for)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/church_app_welcome_helper.rb
# frozen_string_literal: true

module ChurchAppWelcomeHelper
end

app/helpers/pray_petitions_helper.rb
# frozen_string_literal: true

module PrayPetitionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('acmv.png') %>
    <title>ACMV Guapiles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'thank_you.css' %>
    <%= stylesheet_link_tag 'footer.css' %>
    <%= javascript_importmap_tags %>
    <%# <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css"> %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
    <div class="row">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pray_petitions/_form.html.erb
<div class="row">
  <div class="col-12">
    <%= form_with(model: pray_petition) do |form| %>
      <% if pray_petition.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(pray_petition.errors.count, "error") %> prohibited this pray_petition from being saved:</h2>

          <ul>
            <% pray_petition.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-sm-12 col-md-8">
        <%= form.label 'Nombre', class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12 col-md-8">
          <%= form.label 'Teléfono', class: 'form-label' %>
          <%= form.text_field :phone_number, class: 'form-control' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12 col-md-8">
        <%= form.label 'Petición de oración', class: 'form-label' %>
        <%= form.text_area(:pray_for, size: '10x4', class: 'form-control') %>
        </div>
      </div>

      <div class="row privacy-box">
        <div class="col-sm-12 col-md-8">
          <sub>
            *Tu privacidad es importante paran nosotros.
            No compartiremos tu informaci&oacuten con nadie.
          </sub>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12 col-md-8">
          <div class="btn-group" role="group" aria-label="Basic example">
            <%= form.submit 'Enviar Petición', class: "btn btn-success" %>
            <% if current_user.present? %>
              <%= link_to 'Regresar', pray_petitions_path, type: 'button', class: "btn btn-link" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pray_petitions/_pray_petition.html.erb
<div id="<%= dom_id pray_petition %>">
  <p>
    <strong>Name:</strong>
    <%= pray_petition.name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= pray_petition.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= pray_petition.email %>
  </p>

  <p>
    <strong>Pray for:</strong>
    <%= pray_petition.pray_for %>
  </p>

</div>

app/views/pray_petitions/edit.html.erb
<h1>Editing pray petition</h1>

<%= render "form", pray_petition: @pray_petition %>

<br>

<div>
  <%= link_to "Show this pray petition", @pray_petition %> |
  <%= link_to "Back to pray petitions", pray_petitions_path %>
</div>

app/views/pray_petitions/home.html.erb
<div style="text-align: center; top: 100%; position: relative">
  <h3>Asociacion Cristiana Manantial de Vida <br> Guapiles</h3>
</div>

app/views/pray_petitions/index.html.erb
<%= render 'shared/nav_bar' %>
<div class="row justify-content-md-center">
  <p style="color: green"><%= notice %></p>
<div>
</div>
  <h3>Peticiones de oracion</h3>

  <div class="row mb-2">
    <div class="col-4">
      <%= link_to new_pray_petition_path, class: 'btn btn-success' do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
          <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"/>
        </svg> Nueva Peticion
      <% end %>

    </div>
  </div>
  <br/>
  <div class="row">
    <% @pray_petitions.each do |pray_petition| %>
      <div class="col-sm-12 col-md-6">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title"><%= pray_petition.name %></h4>
            <div class="strong"><strong>Fecha: </strong><%= pray_petition.created_at.strftime('%d-%b-%Y') %></div>
            <div class="card-text italic">
              <div class="strong"><strong>Teléfono: </strong><%= pray_petition.phone_number %></div>
            </div>
            <div class="card-text">
              <div class="strong">
                <strong>Petición:</strong>
                <p class="font-italic"><%= pray_petition.pray_for %></p>
              </div>
            </div>
            <%= form_with(model: pray_petition, url: pray_petition_finished_path(pray_petition), method: :post) do |form| %>
              <%= form.button(type: 'submit', class: "btn btn-sm btn-secondary") do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2-circle" viewBox="0 0 16 16">
                  <path d="M2.5 8a5.5 5.5 0 0 1 8.25-4.764.5.5 0 0 0 .5-.866A6.5 6.5 0 1 0 14.5 8a.5.5 0 0 0-1 0 5.5 5.5 0 1 1-11 0z"/>
                  <path d="M15.354 3.354a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l7-7z"/>
                </svg>  Lista
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pray_petitions/new.html.erb
<div class="container">
  <h1>Dejanos tu peticion de oraci&oacute;n</h1>
  <%= render "form", pray_petition: @pray_petition %>
</div>

app/views/pray_petitions/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @pray_petition %>

  <div>
    <%= link_to "Edit this pray petition", edit_pray_petition_path(@pray_petition) %> |
    <%= link_to "Back to pray petitions", pray_petitions_path %>

    <%= button_to "Destroy this pray petition", @pray_petition, method: :delete %>
  </div>
</div>

app/views/pray_petitions/thank_you.html.erb
<% if current_user.present? %>
  <div class="row">
    <div class="col-3">
      <%= link_to "Lista de peticiones", pray_petitions_path, class: "btn btn-link" %>
    </div>
  </div>
<% end %>
<div class="row">
  <h4>Gracias por enviar tu petición. <br>Estaremos orando por ti.</h4>
  <div>
   <p style="font-size: 1em;">
    <i>
    Por nada estén afanosos; más bien, presenten sus peticiones delante de Dios en toda oración y ruego,<br>
    con acción de gracias.
    <br> Y la paz de Dios, que sobrepasa todo entendimiento, guardará sus corazones y sus mentes en Cristo Jesús
   </i>
   <br>
   <sub>Filipenses 4:6-7</sub>
   </p>
  </div>
</div>
<%= link_to "Enviar otra petición", new_pray_petition_path, class: "btn btn-primary" %>

app/views/shared/_footer.html.erb
<p class="footer-heart">
  <sub>Asociacion Cristiana Manantial de Vida, Guapiles <g-emoji class="g-emoji" alias="heart" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2764.png">
  <img class="emoji" alt="heart" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/2764.png"></g-emoji></sub>
  <br>
  <sub>Hector G.Beita - ACMV</sub>
</p>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <a class="navbar-brand" href="#">ACMV Guapiles</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Salir', destroy_user_session_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>